<div class="img-thumbnail" ><img class="img-thumbnail img.fluid" width="350" src= <?=$producto->imagen?>></div>
    <h2 ><?=$producto->producto?></a></h2>
    <h3><?= $producto->categoria?></h3>
    <h4>Descripción del producto:<?= $producto->descripcion?></h4>
    <p>Precio: <?=$producto->precio?></p>
    <p> Stock:<?=  $producto->stock?></p>
    <p>Contacto del proveedor:  <?= $prov->contacto ?></p>
</div> 
