
<form action="deletetipoDeCategoria" method="post" class="mb-3">
    <label class="form-label">Elija la categoria que quiere eliminar</label>
    <select name="categoria" class="form-select">
    <?php foreach ($categorias as $categoria) { ?>
        <option value="<?= $categoria->tipo ?>">
           <?= $categoria->tipo; } ?></option>
           </select> 
    <input type="submit" class="btn btn-primary">
</form>
<a href="volver" class="btn btn-primary">Volver</a>