<form action="nuevoProducto" method = "POST" class="mb-3">
<label class="form-label">Producto</label>
    <input type="text" name="producto" class="form-control">
    <label class="form-label">Categoria</label>
    <input type="text" name="categoria" class="form-control">
    <label class="form-label">Precio</label>
    <input type="number" name="precio" class="form-control">
    <label class="form-label">Descripción</label>
    <input type="text" name="descripcion" class="form-control">
    <label class="form-label">Stock</label>
    <input type="number" name="stock" class="form-control">
    <label class="form-label">Proveedor</label>
    <input type="number" name="proveedor" class="form-control">
    <label class="form-label">Imagen</label>
    <input type="text" name="imagen" class="form-control">
    <input type="submit" class="btn btn-primary">
</form> 
    <a class="btn btn-primary" href="volver">Volver</a>