<h2>Unite a nosotros solicitando ser proveedor!</h2>
        <form action="formProveedor" method="post">
        <label class="form-label">Ingrese su nombre</label><input type="text" name="nombre" class="form-control">
        <label class="form-label">Ingrese su apellido</label><input type="text" name="apellido" class="form-control">
        <label class="form-label">Ingrese su email</label><input type="text" name="email" class="form-control">
        <input type="submit" class="btn btn-primary">
        </form>