<form action="validarSesion" method="post" class="row g-3">
        <div class="col-md-6">
        <label class="form-label">Ingrese su email</label><input type="text" name="email" class="form-control" >
        </div>
        <div class="col-md-6">
        <label class="form-label">Ingrese su contraseña</label><input type="password" name="password" class="form-control">
        </div>
        <div class="col-12">
        <input type="submit" class="btn btn-primary">
        </div>
</form>