<?php session_start() ?>

<!DOCTYPE html>
<html lang="en">
<head>
    <base href="'.BASE_URL.'">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"  integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <ul class="navbar-nav">
            <li class="nav-item"><a class="navbar-brand" href="todos">Productos</a></li>
            <li class="nav-item"><a class="navbar-brand" href="proveedor">Registrate como proveedor</a></li>
            <li class="nav-item"><a class="navbar-brand" href="administracion">Administración</a></li>
            <?php if (!isset($_SESSION['user'])) : ?>
                        <li><a class="btn btn-outline-success" href="login">Login</a></li>
                        <?php else : ?>
                            <li><a class="btn btn-outline-success" href="logout">Logout</a></li>  
                        <?php endif ?>
    </ul>
    </nav>
</body>
</html>