<nav class="navbar navbar-expand-lg bg-body-tertiary ">
    <ul class="navbar-nav">
        <li class="nav-item p-2"><a class = "nav-link" href="add">Agregar producto</a></li>
        <li class="nav-item p-2"><a class = "nav-link" href="update">Modificar producto</a></li>
        <li class="nav-item p-2"><a class = "nav-link" href="delete">Eliminar producto</a></li>
        <li class="nav-item p-2"><a class = "nav-link" href="addCategoria">Agregar categoria</a></li>
        <li class="nav-item p-2"><a class = "nav-link" href="deleteCategoria">Eliminar categoria</a></li>
        <li class="nav-item p-2"><a class = "nav-link" href="updateCategorias">Modificar categoria</a></li>
    </ul>
</nav>